/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:256c96d9-3d81-4fe6-8bbb-9fd81e670b09",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SR9Obib1I",
    "aws_user_pools_web_client_id": "69jho8k2a189ub08hchmj3cuk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qlcasrybenbvjaugarws4ltsnm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ikcdfpuxa5dnbg3uttggpu42f4"
};


export default awsmobile;
